const COMMENTS = [{
    nr: 1,
    ort: "Skigebiet Scuol", //Könnte man ev. als Titel der Popups verwenden
    txt: "Mithilfe des UBEVM könnte speziell im Wintertourismus das Leitbild der nachhaltigen Entwicklung noch stärker etabliert werden. Das Skigebiet könnte als 'das nachhaltigste Skigebiet der Welt' vermarktet werden.",
    lat:46.8289,
    lng:10.2743,
    id: "Vorteil", //ID, um dann die Icons festzulegen
}, {
    nr: 2, //nur zur Übersicht, brauchen wir nicht unbedingt zum einbinden
    ort: "Skigebiet Scuol",
    txt: "Nicht alle Bergbahnenbetreiber*innen können sich mit dem Nachhaltigkeitsgedanken identifizieren und fühlen sich daher in ihren touristischen Angebotsmöglichkeiten eingeschränkt.",
    lat: 46.8289, 
    lng: 10.2993,
    id:"Nachteil", 
},  {
    nr: 3,
    ort: "Gemeinde Valsot",
    txt: "Dort wo noch kein Schutzgebiet ist, wäre Entwicklungspotenzial vorhanden.",
    lat: 46.8643,
    lng: 10.4207,
    id:"Entwicklungsbedarf", 
},   {
    nr: 4,
    ort: "Gemeindegebiet Scuol",
    txt: "Dort wo in der Gemeinde Scuol noch kein UBEVM ist, könnte es noch Entwicklungspotenzial geben.",
    lat: 46.7987,
    lng: 10.3092,
    id:"Entwicklungsbedarf", 
},   {
    nr: 5,
    ort: "Pflegezone",
    txt: "In der gesamten Pflegezone des UBEVM wäre noch Entwicklungspotenzial.",
    lat: 46.7287,
    lng: 10.2396,
    id:"Entwicklungsbedarf", 
},  {
    nr: 6,
    ort: "Pflegezone",
    txt: "Im Gebiet der Pflegezone werden postivie Entwicklungen durch das UBEVM gesehen.",
    lat: 46.7187,
    lng: 10.2100,
    id:"Vorteil", 
}, {
    nr: 7,
    ort: "Ganze Region",
    txt: "In der ganzen Region Engiadina Bassa Val Müstair wird der Landwirtschaftssektor als sehr gut entwickelt angesehen.",
    lat: 46.7699,
    lng: 10.1444,
    id:"Entwickelt", 
},  {
    nr: 8,
    ort: "Unterengadin",
    txt: "Das Unterengadin könnte von einer Vermarktung über das UBEVM profitieren und u. a. die Wertschöpfung landwirtschaftlicher Produkte steigern.",
    lat: 46.7800,
    lng: 10.2114,
    id:"Vorteil", 
}, {
    nr: 9,
    ort: "Siedlungsgebiet Unterengadin",
    txt: "Das Unterengadin könnte vom UBEVM profitieren.",
    lat: 46.8190,
    lng: 10.3826,
    id:"Vorteil", 
}, {
    nr: 10,
    ort: "Kernzone",
    txt: "Die räumliche Trennung der zwei Täler wird als Hindernis für eine gute Zusammenarbeit der Gemeinden gesehen und schlägt sich in Schwierigkeiten der Kommunikation nieder. Hier würde noch Entwicklungsdarf herrschen.",
    lat: 46.6729,
    lng: 10.26310,
    id:"Entwicklungsbedarf", 
}, {
    nr: 11,
    ort: "Kernzone",
    txt: "Der Schweizerische Nationalpark als Kernzone wird als hervorragend aufgestellt und etabliert gesehen.",
    lat: 46.6531,
    lng: 10.1680,
    id:"Entwickelt",
}, {
    nr: 12,
    ort: "Skigebiet Val Müstair",
    txt: "Naturschutzorganisationen werden als Hindernis für eine Erweiterung und einem Ausbau des Skigebietes gesehen und schränken dieses damit in ihren Handlungsmöglichkeiten ein.",
    lat: 46.6464,
    lng: 10.3202,
    id:"Nachteil", 
}, {
    nr: 13,
    ort: "Skigebiet Val Müstair",
    txt: "Durch einen guten Austausch zwischen den Naturschutzorganisationen und dem Skigebiet könnten Vorteile für beide Seiten entstehen.",
    lat: 46.6464,
    lng: 10.3459,
    id:"Vorteil", 
}, {
    nr: 14,
    ort: "Außerhalb des bestehenden Siedlungsraums",
    txt: "Es werden mögliche Einschränkungen durch das UBEVM beim Bau bzw. Ausbau von touristischen Infrastrukturen außerhalb des Siedlungsraumes gesehen.",
    lat: 46.6006,
    lng: 10.3276,
    id:"Nachteil", 
},  {
    nr: 15,
    ort: "Val Müstair",
    txt: "Das Münstertal wird als wirtschaftlich gut entwickelt betrachtet, auch aufgrund von wirtschaftlichen Vorteilen durch das Biosphärenreservat.",
    lat: 46.6120,
    lng: 10.3937,
    id:"Entwickelt", 
}, {
    nr: 15,
    ort: "Entwicklungszone",
    txt: "Es werden positive Effekte für das Gebiet der Entwicklungszone durch das Biosphärenreservat gesehen. Das Tal und insbesondere der Siedlungsraum Val Müstair können somit vom Biosphärenreservat profitieren.",
    lat: 46.5940,
    lng: 10.4331,
    id:"Vorteil", 
},  {
    nr: 16,
    ort: "Entwicklungszone",
    txt: "Die Entwicklungszone des UBEVM wird bereits als sehr gut entwickelt angesehen.",
    lat: 46.6164,
    lng: 10.4431,
    id:"Entwickelt", 
}, {
    nr: 17,
    ort: "Das UBEVM",
    txt: "Das UBEVM wird insbesondere in der aktuellen Größe als vorteilhaft angesehen, da in dieser Größenordung Kommunikaton gut möglich ist. Zudem schafft das UBEVM durch die administrative Vereinigung der beiden Täler ein Zusammengehörigkeitsgefühl.",
    lat: 46.6729,
    lng: 10.2950,
    id:"Vorteil", 
},  {
    nr: 18,
    ort: "Gesamtes bestehendes Biosphärenreservatsgebiet",
    txt: "Das gesamte bisherige Gebiet des UBEVM wird als gut entwickelt angesehen, wobei es durch die Auszeichnung als UBEVM keine Einschränkungen gibt, sondern lediglich Vorteile im Gebiet zu erreichen sind.",
    lat: 46.61761,
    lng: 10.22342,
    id:"Entwickelt", 
},
]